export const randomPrompts = [
  "Portrait of a girl next to a capybara, in the style of a Frida Kahlo painting.",
  "Man with a cowboy hat, in the style of Rene Magritte.",
  "A woman with red hair in the style of Tamara de Lempicka.",
  "Godzilla figurine set against a miniature city, stop-motion.",
  "Pikachu, cinematic, digital art.",
  "Batman, cinematic lighting, high-resolution 3D render.",
  "Storm trooper in the desert, high-detail, dramatic lighting, digital art.",
  "A still life watercolor painting of a hamburger on a table, a window in the background, soft afternoon light.",
  "Retro vector illustration of a neon city skyline.",
  "Ukiyo-e print of two women visiting a shrine.",
  "Cyberpunk style city street at night, Unreal Engine 5.",
  "Oil painting of a cottage near a pond, springtime.",
  "Portrait of a Siamese cat wearing a robe, Chinese watercolor painting.",
  "Portrait of a smiling cyborg woman, peaceful, digital art.",
  "Victorian era portrait of an old man wearing a hat, photorealistic.",
  "Cottage overgrown with ancient trees, high-fantasy, digital art.",
  "Medieval German castle, surrounded by mountains, high fantasy, epic, digital art.",
  "Snail house on top of a cliff, surreal, fantasy, digital art.",
  "A cabin in the woods, isometric pixel art, 64x64, digital art, forest in the background, deer in the foreground.",
  "A photorealistic rendering of an architectural modernist 3 story home, made of concrete, merging with a rocky mountainside, artificially illuminated, soft warm evening.",
  "A photorealistic render of the Louvre Pyramid in Paris, covered in overgrown vines, low-light, evening.",
  "Digital art fine detailed illustration of an alien reaching out a hand, floating in space.",
  "A Lovecraftian monster with a squid head and human body, color sketch, haunting low light, red and blue accents, rough texture.",
  "An ugly ogre with gray-green pocked skin, inspired by Dark Souls, Unreal Engine 5 3D render, black background, disgruntled.",
  "Fractal art, spiraling, pastel color palette, digital art.",
  "Black hyper glossy ferrofluids, light pink background.",
  "Hands, generative art, large-scale repetition, 3D render, multi-colored.",
  "Portrait of a child playing in a park, using natural lighting and candid expressions.",
  "Portrait of a military veteran in uniform, with strong, directional lighting.",
  "Portrait of a street performer in action with a bustling city as a blurred background.",
  "Stylized portrait of an entrepreneur against a city skyline, with dramatic lighting and a futuristic look.",
  "Portrait of a professional dancer expressing emotion through movement, with dramatic lighting.",
  "Design a unique playable character, outlining their appearance, abilities, and personality for a protagonist in Genshin Impact.",
  "Create a powerful superhero character in the style of a comic book, complete with bold outlines and vibrant colors.",
  "Create an anime character with large, detailed eyes and distinctive Japanese anime aesthetics.",
  "Craft mandalas incorporating vibrant colors and unique patterns that will inspire feelings of happiness and well-being.",
  "Generate visuals of dynamic keynote speakers captivating the audience at your conference. Capture the excitement of professionals networking and exchanging ideas at an event in a photograph.",
  "Generate a logo for a business.",
  "Iron man, cinematic lighting, high resolution 3D render",
  "Photoshoot of an e-girl promoting some makeup product.",
];
