export const randomPrompts = [
  "Portrait of a girl next to a capybara, in the style of a Frida Kahlo painting.",
  "Man with a cowboy hat, in the style of Rene Magritte.",
  "A woman with red hair in the style of Tamara de Lempicka.",
  "A woman with brunette  hair in the style of Adriana Lima.",
  "Godzilla figurine set against a miniature city, stop-motion.",
  "Pikachu, cinematic, digital art.",
  "Batman, cinematic lighting, high-resolution 3D render.",
  "Storm trooper in the desert, high-detail, dramatic lighting, digital art.",
  "A still life watercolor painting of a hamburger on a table, a window in the background, soft afternoon light.",
  "Retro vector illustration of a neon city skyline.",
  "Cyberpunk style city street at night, Unreal Engine 5.",
  "Oil painting of a cottage near a pond, springtime.",
  "Portrait of a Siamese cat wearing a robe, Chinese watercolor painting.",
  "Portrait of a smiling cyborg woman, peaceful, digital art.",
  "Victorian era portrait of an old man wearing a hat, photorealistic.",
  "Cottage overgrown with ancient trees, high-fantasy, digital art.",
  "Medieval German castle, surrounded by mountains, high fantasy, epic, digital art.",
  "Snail house on top of a cliff, surreal, fantasy, digital art.",
  "A photorealistic rendering of an architectural modernist 3 story home, made of concrete, merging with a rocky mountainside, artificially illuminated, soft warm evening.",
  "A photorealistic render of the Louvre Pyramid in Paris, covered in overgrown vines, low-light, evening.",
  "Digital art fine detailed illustration of an alien reaching out a hand, floating in space.",
  "A Lovecraftian monster with a squid head and human body, color sketch, haunting low light, red and blue accents, rough texture.",
  "An ugly ogre with gray-green pocked skin, inspired by Dark Souls, Unreal Engine 5 3D render, black background, disgruntled.",
  "Fractal art, spiraling, pastel color palette, digital art.",
  "Hands, generative art, large-scale repetition, 3D render, multi-colored.",
  "Portrait of a child playing in a park, using natural lighting and candid expressions.",
  "Portrait of a military veteran in uniform, with strong, directional lighting.",
  "Portrait of a street performer in action with a bustling city as a blurred background.",
  "Stylized portrait of an entrepreneur against a city skyline, with dramatic lighting and a futuristic look.",
  "Portrait of a professional dancer expressing emotion through movement, with dramatic lighting.",
  "Design a unique playable character, outlining their appearance, abilities, and personality for a protagonist in Genshin Impact.",
  "Create a powerful superhero character in the style of a comic book, complete with bold outlines and vibrant colors.",
  "Create an anime character with large, detailed eyes and distinctive Japanese anime aesthetics.",
  "Craft mandalas incorporating vibrant colors and unique patterns that will inspire feelings of happiness and well-being.",
  "Generate visuals of dynamic keynote speakers captivating the audience at your conference. Capture the excitement of professionals networking and exchanging ideas at an event in a photograph.",
  "Iron man, cinematic lighting, high resolution 3D render",
  "Photoshoot of an e-girl promoting some makeup product.",
  "Abstract painting of a dreamscape, swirling colors and surreal shapes.",
  "A steampunk-inspired airship soaring through the clouds, intricate details, digital art.",
  "Portrait of a wise old owl wearing glasses, perched on a stack of books, traditional oil painting.",
  "Futuristic cityscape with flying cars and holographic billboards, night scene, digital art.",
  "A serene underwater scene with colorful coral reefs and exotic fish, watercolor illustration.",
  "A group of friends around a bonfire on a beach, capturing the warmth and joy of the moment.",
  "A majestic dragon curled around a medieval castle, epic fantasy scene, digital art.",
  "A surreal landscape with floating islands and waterfalls, inspired by fantasy realms, digital painting.",
  "Concept art for a sci-fi alien civilization, with unique architecture and advanced technology.",
  "Abstract geometric pattern with vibrant colors, digital design.",
  "A vintage typewriter surrounded by floating words, representing creativity and storytelling.",
  "Portrait of a mystic sorcerer in a mystical forest, glowing runes and magical elements, digital art.",
  "A spaceship exploring a distant galaxy, cosmic adventure, digital illustration.",
  "A retro-style poster for a fictitious travel destination on a distant planet, with a futuristic twist.",
  "Detailed close-up of a bee pollinating a flower, macro photography.",
  "A whimsical illustration of talking animals in a forest, inspired by children's literature.",
  "A cyberpunk-inspired robot with neon lights and metallic textures, 3D rendering.",
  "Abstract representation of the concept of time, with clock faces and swirling hourglasses.",
  "A serene mountain landscape with a tranquil lake, watercolor painting.",
  "Concept art for a futuristic city park, blending nature and technology.",
  "A vintage film camera capturing a candid moment in a bustling city street.",
  "A magical library with floating books and glowing orbs, fantasy digital painting.",
  "Abstract composition of intersecting lines and shapes, exploring balance and symmetry.",
  "A minimalist illustration of a single tree in a vast desert, symbolizing resilience.",
  "A surreal depiction of a melting clock, inspired by Salvador Dali's iconic artwork.",
  "A steampunk-inspired robotic arm, combining Victorian aesthetics with modern technology.",
  "A whimsical illustration of a tea party with anthropomorphic animals, inspired by Lewis Carroll.",
  "Concept art for a futuristic skyscraper with unique architectural features, digital rendering.",
  "A playful illustration of a cat wearing sunglasses and enjoying a sunny day, cartoon style.",
  "Abstract representation of the concept of dreams, with floating clouds and ethereal elements.",
  "A futuristic racing car speeding through a neon-lit track, dynamic and high-energy.",
  "A tranquil scene of a boat drifting on a calm lake at sunset, capturing the beauty of nature.",
  "A mysterious doorway leading to a magical realm, with glowing symbols and intricate details.",
];
